// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoD64Fm9rC-zjQoZWL0ri1DW02fCmp5I',
    appId: '1:976228520694:web:31b8ec3ccedff28046d2d7',
    messagingSenderId: '976228520694',
    projectId: 'flutter-chat-e5c62',
    authDomain: 'flutter-chat-e5c62.firebaseapp.com',
    storageBucket: 'flutter-chat-e5c62.appspot.com',
    measurementId: 'G-SX013MY3PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoOhjDfsluiaIN9bf-WjXCRZ6fqGuqlRw',
    appId: '1:976228520694:android:d3c89958d966a86e46d2d7',
    messagingSenderId: '976228520694',
    projectId: 'flutter-chat-e5c62',
    storageBucket: 'flutter-chat-e5c62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkNyLZYbbhRlMU1OQQUlxkOCO7U6pqjwI',
    appId: '1:976228520694:ios:d7fdd29bb5c1e0df46d2d7',
    messagingSenderId: '976228520694',
    projectId: 'flutter-chat-e5c62',
    storageBucket: 'flutter-chat-e5c62.appspot.com',
    iosClientId: '976228520694-0o4nnu2pg2gpb8hvov8l9s8qi8k0528l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkNyLZYbbhRlMU1OQQUlxkOCO7U6pqjwI',
    appId: '1:976228520694:ios:d7fdd29bb5c1e0df46d2d7',
    messagingSenderId: '976228520694',
    projectId: 'flutter-chat-e5c62',
    storageBucket: 'flutter-chat-e5c62.appspot.com',
    iosClientId: '976228520694-0o4nnu2pg2gpb8hvov8l9s8qi8k0528l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
